(annotation-annotate 1 155 '(comment) nil)
(annotation-annotate 156 162 '(keyword) nil)
(annotation-annotate 163 178 '(module operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 163))
(annotation-annotate 179 184 '(keyword) nil)
(annotation-annotate 186 190 '(keyword) nil)
(annotation-annotate 191 193 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 191))
(annotation-annotate 194 195 '(symbol) nil)
(annotation-annotate 196 199 '(primitivetype) nil)
(annotation-annotate 200 205 '(keyword) nil)
(annotation-annotate 208 209 '(inductiveconstructor) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 208))
(annotation-annotate 216 217 '(symbol) nil)
(annotation-annotate 218 220 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 191))
(annotation-annotate 223 227 '(inductiveconstructor) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 223))
(annotation-annotate 231 232 '(symbol) nil)
(annotation-annotate 233 235 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 191))
(annotation-annotate 236 238 '(symbol) nil)
(annotation-annotate 239 241 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 191))
(annotation-annotate 244 248 '(inductiveconstructor) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 244))
(annotation-annotate 252 253 '(symbol) nil)
(annotation-annotate 254 256 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 191))
(annotation-annotate 257 259 '(symbol) nil)
(annotation-annotate 260 262 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 191))
(annotation-annotate 266 270 '(keyword) nil)
(annotation-annotate 271 276 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 271))
(annotation-annotate 277 278 '(symbol) nil)
(annotation-annotate 279 281 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 191))
(annotation-annotate 282 284 '(symbol) nil)
(annotation-annotate 285 288 '(primitivetype) nil)
(annotation-annotate 289 294 '(keyword) nil)
(annotation-annotate 297 300 '(inductiveconstructor operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 297))
(annotation-annotate 305 306 '(symbol) nil)
(annotation-annotate 307 312 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 271))
(annotation-annotate 313 314 '(inductiveconstructor) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 208))
(annotation-annotate 317 320 '(inductiveconstructor operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 317))
(annotation-annotate 325 326 '(symbol) nil)
(annotation-annotate 327 328 '(symbol) nil)
(annotation-annotate 328 329 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 328))
(annotation-annotate 330 331 '(symbol) nil)
(annotation-annotate 332 334 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 191))
(annotation-annotate 334 335 '(symbol) nil)
(annotation-annotate 336 338 '(symbol) nil)
(annotation-annotate 339 344 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 271))
(annotation-annotate 345 346 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 328))
(annotation-annotate 347 349 '(symbol) nil)
(annotation-annotate 350 355 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 271))
(annotation-annotate 356 357 '(symbol) nil)
(annotation-annotate 357 361 '(inductiveconstructor) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 223))
(annotation-annotate 362 363 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 328))
(annotation-annotate 363 364 '(symbol) nil)
(annotation-annotate 366 370 '(keyword) nil)
(annotation-annotate 371 375 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 371))
(annotation-annotate 376 377 '(symbol) nil)
(annotation-annotate 378 380 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 191))
(annotation-annotate 381 383 '(symbol) nil)
(annotation-annotate 384 386 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 191))
(annotation-annotate 387 389 '(symbol) nil)
(annotation-annotate 390 393 '(primitivetype) nil)
(annotation-annotate 394 399 '(keyword) nil)
(annotation-annotate 403 409 '(inductiveconstructor operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 403))
(annotation-annotate 418 419 '(symbol) nil)
(annotation-annotate 420 421 '(symbol) nil)
(annotation-annotate 421 422 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 421))
(annotation-annotate 423 424 '(symbol) nil)
(annotation-annotate 425 427 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 191))
(annotation-annotate 427 428 '(symbol) nil)
(annotation-annotate 429 431 '(symbol) nil)
(annotation-annotate 432 433 '(symbol) nil)
(annotation-annotate 433 434 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 433))
(annotation-annotate 435 436 '(symbol) nil)
(annotation-annotate 437 439 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 191))
(annotation-annotate 439 440 '(symbol) nil)
(annotation-annotate 441 443 '(symbol) nil)
(annotation-annotate 464 468 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 371))
(annotation-annotate 469 470 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 421))
(annotation-annotate 471 472 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 433))
(annotation-annotate 473 475 '(symbol) nil)
(annotation-annotate 476 480 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 371))
(annotation-annotate 481 482 '(symbol) nil)
(annotation-annotate 482 486 '(inductiveconstructor) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 223))
(annotation-annotate 487 488 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 421))
(annotation-annotate 488 489 '(symbol) nil)
(annotation-annotate 490 491 '(symbol) nil)
(annotation-annotate 491 495 '(inductiveconstructor) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 223))
(annotation-annotate 496 497 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 433))
(annotation-annotate 497 498 '(symbol) nil)
(annotation-annotate 501 512 '(inductiveconstructor operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 501))
(annotation-annotate 516 517 '(symbol) nil)
(annotation-annotate 518 522 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 371))
(annotation-annotate 523 524 '(symbol) nil)
(annotation-annotate 524 528 '(inductiveconstructor) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 244))
(annotation-annotate 529 530 '(inductiveconstructor) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 208))
(annotation-annotate 530 531 '(symbol) nil)
(annotation-annotate 532 533 '(inductiveconstructor) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 208))
(annotation-annotate 536 547 '(inductiveconstructor operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 536))
(annotation-annotate 551 552 '(symbol) nil)
(annotation-annotate 553 554 '(symbol) nil)
(annotation-annotate 554 555 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 554))
(annotation-annotate 556 557 '(symbol) nil)
(annotation-annotate 558 560 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 191))
(annotation-annotate 560 561 '(symbol) nil)
(annotation-annotate 562 564 '(symbol) nil)
(annotation-annotate 565 570 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 271))
(annotation-annotate 571 572 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 554))
(annotation-annotate 573 575 '(symbol) nil)
(annotation-annotate 576 580 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 371))
(annotation-annotate 581 582 '(symbol) nil)
(annotation-annotate 582 586 '(inductiveconstructor) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 244))
(annotation-annotate 587 588 '(symbol) nil)
(annotation-annotate 588 592 '(inductiveconstructor) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 223))
(annotation-annotate 593 594 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 554))
(annotation-annotate 594 596 '(symbol) nil)
(annotation-annotate 597 598 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 554))
(annotation-annotate 601 607 '(inductiveconstructor operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 601))
(annotation-annotate 616 617 '(symbol) nil)
(annotation-annotate 618 619 '(symbol) nil)
(annotation-annotate 619 620 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 619))
(annotation-annotate 621 622 '(symbol) nil)
(annotation-annotate 623 625 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 191))
(annotation-annotate 625 626 '(symbol) nil)
(annotation-annotate 627 629 '(symbol) nil)
(annotation-annotate 630 631 '(symbol) nil)
(annotation-annotate 631 632 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 631))
(annotation-annotate 633 634 '(symbol) nil)
(annotation-annotate 635 637 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 191))
(annotation-annotate 637 638 '(symbol) nil)
(annotation-annotate 639 641 '(symbol) nil)
(annotation-annotate 662 666 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 371))
(annotation-annotate 667 668 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 619))
(annotation-annotate 669 670 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 631))
(annotation-annotate 671 673 '(symbol) nil)
(annotation-annotate 674 678 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 371))
(annotation-annotate 679 680 '(symbol) nil)
(annotation-annotate 680 684 '(inductiveconstructor) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 244))
(annotation-annotate 685 686 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 619))
(annotation-annotate 686 687 '(symbol) nil)
(annotation-annotate 688 689 '(symbol) nil)
(annotation-annotate 689 693 '(inductiveconstructor) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 244))
(annotation-annotate 694 695 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 631))
(annotation-annotate 695 696 '(symbol) nil)
(annotation-annotate 698 702 '(keyword) nil)
(annotation-annotate 703 705 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 703))
(annotation-annotate 706 707 '(symbol) nil)
(annotation-annotate 708 710 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 191))
(annotation-annotate 711 713 '(symbol) nil)
(annotation-annotate 714 716 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 191))
(annotation-annotate 717 719 '(symbol) nil)
(annotation-annotate 720 723 '(primitivetype) nil)
(annotation-annotate 724 729 '(keyword) nil)
(annotation-annotate 732 735 '(inductiveconstructor) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 732))
(annotation-annotate 736 737 '(symbol) nil)
(annotation-annotate 738 739 '(symbol) nil)
(annotation-annotate 739 740 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 739))
(annotation-annotate 741 742 '(symbol) nil)
(annotation-annotate 743 745 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 191))
(annotation-annotate 745 746 '(symbol) nil)
(annotation-annotate 747 749 '(symbol) nil)
(annotation-annotate 750 752 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 703))
(annotation-annotate 754 755 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 739))
(annotation-annotate 756 757 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 739))
(annotation-annotate 759 811 '(comment) nil)
(annotation-annotate 813 817 '(keyword) nil)
(annotation-annotate 818 823 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 818))
(annotation-annotate 824 825 '(symbol) nil)
(annotation-annotate 826 829 '(primitivetype) nil)
(annotation-annotate 830 835 '(keyword) nil)
(annotation-annotate 837 853 '(function operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 837))
(annotation-annotate 854 855 '(symbol) nil)
(annotation-annotate 856 857 '(symbol) nil)
(annotation-annotate 857 858 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 857))
(annotation-annotate 859 860 '(symbol) nil)
(annotation-annotate 861 863 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 191))
(annotation-annotate 863 864 '(symbol) nil)
(annotation-annotate 865 867 '(symbol) nil)
(annotation-annotate 868 869 '(symbol) nil)
(annotation-annotate 869 871 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 869))
(annotation-annotate 872 873 '(symbol) nil)
(annotation-annotate 874 876 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 191))
(annotation-annotate 876 877 '(symbol) nil)
(annotation-annotate 878 880 '(symbol) nil)
(annotation-annotate 881 885 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 371))
(annotation-annotate 886 887 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 857))
(annotation-annotate 888 890 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 869))
(annotation-annotate 891 893 '(symbol) nil)
(annotation-annotate 894 899 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 271))
(annotation-annotate 900 901 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 857))
(annotation-annotate 903 905 '(symbol) nil)
(annotation-annotate 906 911 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 818))
(annotation-annotate 914 930 '(function operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 837))
(annotation-annotate 931 933 '(symbol) nil)
(annotation-annotate 943 944 '(symbol) nil)
(annotation-annotate 944 947 '(inductiveconstructor operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 297))
(annotation-annotate 947 948 '(symbol) nil)
(annotation-annotate 949 965 '(function operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 837))
(annotation-annotate 966 967 '(symbol) nil)
(annotation-annotate 967 973 '(inductiveconstructor operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 403))
(annotation-annotate 974 975 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 974))
(annotation-annotate 975 976 '(symbol) nil)
(annotation-annotate 978 979 '(symbol) nil)
(annotation-annotate 979 982 '(inductiveconstructor operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 317))
(annotation-annotate 983 985 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 983))
(annotation-annotate 985 986 '(symbol) nil)
(annotation-annotate 990 991 '(symbol) nil)
(annotation-annotate 992 1008 '(function operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 837))
(annotation-annotate 1009 1010 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 974))
(annotation-annotate 1012 1014 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 983))
(annotation-annotate 1016 1019 '(function) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1016))
(annotation-annotate 1020 1021 '(symbol) nil)
(annotation-annotate 1022 1023 '(symbol) nil)
(annotation-annotate 1023 1024 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1023))
(annotation-annotate 1025 1026 '(symbol) nil)
(annotation-annotate 1027 1029 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 191))
(annotation-annotate 1029 1030 '(symbol) nil)
(annotation-annotate 1031 1033 '(symbol) nil)
(annotation-annotate 1034 1035 '(symbol) nil)
(annotation-annotate 1035 1037 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1035))
(annotation-annotate 1038 1039 '(symbol) nil)
(annotation-annotate 1040 1042 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 191))
(annotation-annotate 1042 1043 '(symbol) nil)
(annotation-annotate 1044 1046 '(symbol) nil)
(annotation-annotate 1047 1048 '(symbol) nil)
(annotation-annotate 1048 1050 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1048))
(annotation-annotate 1051 1052 '(symbol) nil)
(annotation-annotate 1053 1055 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 191))
(annotation-annotate 1055 1056 '(symbol) nil)
(annotation-annotate 1057 1059 '(symbol) nil)
(annotation-annotate 1066 1070 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 371))
(annotation-annotate 1071 1072 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1023))
(annotation-annotate 1073 1075 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1035))
(annotation-annotate 1076 1078 '(symbol) nil)
(annotation-annotate 1079 1083 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 371))
(annotation-annotate 1084 1085 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1023))
(annotation-annotate 1086 1088 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1048))
(annotation-annotate 1089 1091 '(symbol) nil)
(annotation-annotate 1092 1094 '(datatype) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 703))
(annotation-annotate 1095 1097 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1035))
(annotation-annotate 1098 1100 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1048))
(annotation-annotate 1102 1105 '(function) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1016))
(annotation-annotate 1106 1107 '(symbol) nil)
(annotation-annotate 1107 1113 '(inductiveconstructor operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 403))
(annotation-annotate 1114 1115 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1114))
(annotation-annotate 1115 1116 '(symbol) nil)
(annotation-annotate 1125 1126 '(symbol) nil)
(annotation-annotate 1126 1132 '(inductiveconstructor operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 403))
(annotation-annotate 1133 1135 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1133))
(annotation-annotate 1135 1136 '(symbol) nil)
(annotation-annotate 1146 1150 '(keyword) nil)
(annotation-annotate 1151 1154 '(function) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1016))
(annotation-annotate 1155 1156 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1114))
(annotation-annotate 1157 1159 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1133))
(annotation-annotate 1160 1163 '(symbol) nil)
(annotation-annotate 1164 1165 '(symbol) nil)
(annotation-annotate 1166 1169 '(inductiveconstructor) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 732))
(annotation-annotate 1170 1171 '(symbol) nil)
(annotation-annotate 1172 1175 '(inductiveconstructor) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 732))
(annotation-annotate 1176 1179 '(function) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1016))
(annotation-annotate 1180 1181 '(symbol) nil)
(annotation-annotate 1181 1192 '(inductiveconstructor operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 501))
(annotation-annotate 1192 1193 '(symbol) nil)
(annotation-annotate 1199 1200 '(symbol) nil)
(annotation-annotate 1200 1211 '(inductiveconstructor operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 501))
(annotation-annotate 1211 1212 '(symbol) nil)
(annotation-annotate 1218 1219 '(symbol) nil)
(annotation-annotate 1220 1223 '(inductiveconstructor) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 732))
(annotation-annotate 1224 1227 '(function) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1016))
(annotation-annotate 1228 1229 '(symbol) nil)
(annotation-annotate 1229 1240 '(inductiveconstructor operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 536))
(annotation-annotate 1241 1243 '(symbol) nil)
(annotation-annotate 1247 1248 '(symbol) nil)
(annotation-annotate 1248 1259 '(inductiveconstructor operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 536))
(annotation-annotate 1260 1262 '(symbol) nil)
(annotation-annotate 1266 1267 '(symbol) nil)
(annotation-annotate 1268 1271 '(inductiveconstructor) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 732))
(annotation-annotate 1272 1275 '(function) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1016))
(annotation-annotate 1276 1277 '(symbol) nil)
(annotation-annotate 1277 1283 '(inductiveconstructor operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 601))
(annotation-annotate 1284 1285 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1284))
(annotation-annotate 1285 1286 '(symbol) nil)
(annotation-annotate 1295 1296 '(symbol) nil)
(annotation-annotate 1296 1302 '(inductiveconstructor operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 601))
(annotation-annotate 1303 1305 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1303))
(annotation-annotate 1305 1306 '(symbol) nil)
(annotation-annotate 1316 1320 '(keyword) nil)
(annotation-annotate 1321 1324 '(function) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1016))
(annotation-annotate 1325 1326 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1284))
(annotation-annotate 1327 1329 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1303))
(annotation-annotate 1330 1333 '(symbol) nil)
(annotation-annotate 1334 1335 '(symbol) nil)
(annotation-annotate 1336 1339 '(inductiveconstructor) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 732))
(annotation-annotate 1340 1341 '(symbol) nil)
(annotation-annotate 1342 1345 '(inductiveconstructor) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 732))
(annotation-annotate 1346 1374 '(comment) nil)
(annotation-annotate 1375 1378 '(function) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1016))
(annotation-annotate 1379 1380 '(symbol) nil)
(annotation-annotate 1380 1386 '(inductiveconstructor operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 601))
(annotation-annotate 1387 1388 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1387))
(annotation-annotate 1388 1389 '(symbol) nil)
(annotation-annotate 1398 1399 '(symbol) nil)
(annotation-annotate 1399 1410 '(inductiveconstructor operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 536))
(annotation-annotate 1411 1413 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1411))
(annotation-annotate 1413 1414 '(symbol) nil)
(annotation-annotate 1419 1423 '(keyword) nil)
(annotation-annotate 1424 1440 '(function operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 837))
(annotation-annotate 1441 1442 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1387))
(annotation-annotate 1443 1444 '(symbol) nil)
(annotation-annotate 1444 1447 '(inductiveconstructor operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 317))
(annotation-annotate 1448 1450 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1411))
(annotation-annotate 1450 1451 '(symbol) nil)
(annotation-annotate 1452 1455 '(symbol) nil)
(annotation-annotate 1456 1457 '(symbol) nil)
(annotation-annotate 1458 1460 '(symbol) nil)
(annotation-annotate 1461 1464 '(function) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1016))
(annotation-annotate 1465 1466 '(symbol) nil)
(annotation-annotate 1466 1477 '(inductiveconstructor operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 536))
(annotation-annotate 1478 1480 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1478))
(annotation-annotate 1480 1481 '(symbol) nil)
(annotation-annotate 1484 1485 '(symbol) nil)
(annotation-annotate 1485 1491 '(inductiveconstructor operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 601))
(annotation-annotate 1492 1493 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1492))
(annotation-annotate 1493 1494 '(symbol) nil)
(annotation-annotate 1505 1509 '(keyword) nil)
(annotation-annotate 1510 1526 '(function operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 837))
(annotation-annotate 1527 1528 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1492))
(annotation-annotate 1529 1530 '(symbol) nil)
(annotation-annotate 1530 1533 '(inductiveconstructor operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 317))
(annotation-annotate 1534 1536 '(bound) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1478))
(annotation-annotate 1536 1537 '(symbol) nil)
(annotation-annotate 1538 1541 '(symbol) nil)
(annotation-annotate 1542 1543 '(symbol) nil)
(annotation-annotate 1544 1546 '(symbol) nil)
(annotation-annotate 1547 1550 '(function) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1016))
(annotation-annotate 1551 1552 '(symbol) nil)
(annotation-annotate 1552 1558 '(inductiveconstructor operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 601))
(annotation-annotate 1559 1562 '(symbol) nil)
(annotation-annotate 1570 1571 '(symbol) nil)
(annotation-annotate 1571 1582 '(inductiveconstructor operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 501))
(annotation-annotate 1582 1583 '(symbol) nil)
(annotation-annotate 1584 1587 '(function) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 1016))
(annotation-annotate 1588 1589 '(symbol) nil)
(annotation-annotate 1589 1600 '(inductiveconstructor operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 501))
(annotation-annotate 1600 1601 '(symbol) nil)
(annotation-annotate 1607 1608 '(symbol) nil)
(annotation-annotate 1608 1614 '(inductiveconstructor operator) nil '("/home/bpientka/Projects/fphoas/papers/coverage/electronic_appendix/agda/TAPL_ARITH_ONLY.agda" . 601))
(annotation-annotate 1615 1618 '(symbol) nil)
